name: iOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
      
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_11.app
      
    - name: Installing Homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      
    - name: Installing Java 8
      run: brew tap adoptopenjdk/openjdk && brew cask install adoptopenjdk/openjdk/adoptopenjdk8     
      
    - name: Installing Gradle
      run: brew install gradle    
      
    - name: Installing Android Studio
      run: brew cask install android-sdk    
    
    - name: Setting Variables
      run: |
        export GRADLE_HOME=/usr/local/opt/gradle
        export ANDROID_HOME=/usr/local/share/android-sdk
        export PATH=$GRADLE_HOME/bin:$PATH
        export PATH=$ANDROID_HOME/tools:$PATH
        export PATH=$ANDROID_HOME/platform-tools:$PATH
        
    - name: Download Buildtools 28.0.3
      run: sdkmanager "build-tools;28.0.3" 
       
    - name: Download Android 28       
      run: sdkmanager "platforms;android-28"

    - name: Adding Build tools to Path
      run: export PATH=$ANDROID_HOME/build-tools/$(ls -tr $ANDROID_HOME/build-tools/ | tail -1):$PATH
      
    #- name: Accepting Android license
    #  run: yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || if [ $? -ne '0' ]; then exit 0; fi;
      #   #Captures SIGPIPE 141 error but still allow repeating "y" to accept all licenses
      
    - name: Installing NodeJS
      run: brew install node
      
    - name: Yarn Install
      run: yarn install      
      
    - name: Pod Install 
      run: |
        cd ios
        pod repo update
        pod install
      shell: bash
    - uses: ty0x2333/cocoapods-action@master
