name: iOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
      
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_11.app
      
    - name: Installing Homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      
    - name: Installing Java
      run: brew tap adoptopenjdk/openjdk && brew cask install adoptopenjdk/openjdk/adoptopenjdk8     
      
    - name: Installing Android Studio
      run: | 
        brew install ant
        brew install maven
        brew install gradle
        brew cask install android-sdk  
      
    - name: Accepting license
      run: android update sdk --no-ui  
    
    - name: Setting Variables
      run: |
        export ANT_HOME=/usr/local/opt/ant
        export MAVEN_HOME=/usr/local/opt/maven
        export GRADLE_HOME=/usr/local/opt/gradle
        export ANDROID_HOME=/usr/local/opt/android-sdk
        export PATH=$ANT_HOME/bin:$PATH
        export PATH=$MAVEN_HOME/bin:$PATH
        export PATH=$GRADLE_HOME/bin:$PATH
        export PATH=$ANDROID_HOME/tools:$PATH
        export PATH=$ANDROID_HOME/platform-tools:$PATH
        export PATH=$ANDROID_HOME/build-tools/$(ls -tr $ANDROID_HOME/build-tools/ | tail -1):$PATH
      
    - name: Installing node
      run: brew install node
      
    - name: Install Yarn Dependencies
      run: yarn install      
      
    - name: Install Dependences
      run: |
        cd ios
        pod repo update
        pod install
      shell: bash
    - uses: ty0x2333/cocoapods-action@master
