name: iOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
      
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_11.app
      
    - name: Installing Homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      
    - name: Installing node
      run: brew install node  
      
    - name: Installing Java
      run: brew tap adoptopenjdk/openjdk && brew cask install adoptopenjdk8  
      
    - name: Install Dependencies
      run: yarn install      
      
    - name: Install Dependences
      run: |
        cd ios
        pod repo update
        pod install
      shell: bash
    - uses: ty0x2333/cocoapods-action@master
