name: Jest Test Runner

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [12, 13]

    runs-on: ubuntu-latest
    container: node:13


    steps:
    - uses: actions/checkout@v2
    - run: yarn
    - run: yarn test
      env:
        CI: true
