name: Lint

on:
  pull_request:
    branches:
      - develop
      - release-candidate
      - master

jobs:
  diffs-pass-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache node_modules/
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-cache-

      - run: yarn --frozen-lockfile

      - uses: 18F/github-action-eslint@1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
