name: Lint

on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"

      - name: echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}

      - uses: 18F/github-action-eslint@1.0.0
        with:
          files: ${{ steps.getfile.outputs.files }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
