name: Lint

on:
  pull_request:
    branches:
      - develop
      - release-candidate
      - master

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache node_modules/
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-cache-

      - run: yarn --frozen-lockfile

      # The above eslint action does not show you in the job log what failed,
      # this is just for debugging purposes
      - run: yarn lint
        if: ${{ always() }}
