name: Lint

on:
  pull_request:
    branches:
      - develop
      - release-candidate
      - master

jobs:
  diffs-pass-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: 18F/github-action-eslint@1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
